#!/usr/bin/env sh
set -e

ARCH=`uname -m`

echo "Detected architecture: $ARCH."
docker build \
  --build-arg ARCH=$ARCH \
  --tag astroswarm/websockify-$ARCH:latest \
 ./

echo "Would you like to release this image now (y/n)?"
read release
if [ $release = "y" ]; then
  echo "Pushing to AstroSwarm registry."
  docker push astroswarm/websockify-$ARCH:latest
fi
